runtime: python311
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: blinker
  version: 1.7.0
- name: cachelib
  version: 0.9.0
- name: cachetools
  version: 5.3.2        
- name: certifi
  version: 2024.2.2        
- name: charset-normalizer
  version: 3.3.2
- name: click
  version: 8.1.7
- name: colorama
  version: 0.4.6
- name: Flask
  version: 3.0.2
- name: Flask-Caching
  version: 2.1.0
- name: google-api-core
  version: 2.17.0
- name: google-api-python-client
  version: 2.117.0
- name: google-auth
  version: 2.27.0
- name: google-auth-httplib2
  version: 0.2.0
- name: googleapis-common-protos
  version: 1.62.0
- name: httplib2
  version: 0.22.0
- name: idna
  version: 3.6
- name: importlib-metadata
  version: 7.0.1
- name: itsdangerous
  version: 2.1.2
- name: Jinja2
  version: 3.1.3
- name: MarkupSafe
  version: 2.1.5
- name: numpy
  version: 1.26.4
- name: pandas
  version: 2.2.1
- name: protobuf
  version: 4.25.2
- name: pyasn1
  version: 0.5.1
- name: pyasn1-modules
  version: 0.3.0
- name: pyparsing
  version: 3.1.1
- name: python-dateutil
  version: 2.8.2
- name: pytz
  version: 2024.1
- name: requests
  version: 2.31.0
- name: rsa
  version: 4.9
- name: six
  version: 1.16.0
- name: tzdata
  version: 2024.1
- name: uritemplate
  version: 4.1.1
- name: urllib3
  version: 2.2.0
- name: Werkzeug
  version: 3.0.1
- name: zipp
  version: 3.17.0